### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Davhed** [lukaszdk/texture-atlas-generator#2]
I know the issues list is not the ideal place for this, but thank you for providing this code. It was a fantastic reference and guide for me when creating a atlas capabilities for the OpenGL ES framework, Rajawali. 

Here is the resulting class for your gratification:
[Rajawali Texture Packer](https://github.com/Davhed/Rajawali/blob/texture_packing/src/rajawali/materials/TexturePacker.java)

**Comment by lukaszdk** [comment]
I am glad you it was helpful to you.
